local style = require "core.style"
local common = require "core.common"

style.background        = { common.color "#1d2021" }
style.background2       = { common.color "#282828" }
style.background3       = { common.color "#3c3836" }
style.text              = { common.color "#ebdbb2" }
style.caret             = { common.color "#ebdbb2" }
style.accent            = { common.color "#458588" }
style.dim               = { common.color "#928374" }
style.divider           = { common.color "#1d2021" }
style.selection         = { common.color "#504945" }
style.line_number       = { common.color "#665c54" }
style.line_number2      = { common.color "#a89984" }
style.line_highlight    = { common.color "#32302f" }
style.scrollbar         = { common.color "#3c3836" }
style.scrollbar2        = { common.color "#504945" }
style.scrollbar_track   = { common.color "#1d2021" }
style.nagbar            = { common.color "#cc241d" }
style.nagbar_text       = { common.color "#ebdbb2" }
style.nagbar_dim        = { common.color "#9d0006" }
style.drag_overlay      = { common.color "#1d202180" }
style.drag_overlay_tab  = { common.color "#45858840" }
style.good              = { common.color "#b8bb26" }
style.warn              = { common.color "#fabd2f" }
style.error             = { common.color "#fb4934" }
style.modified          = { common.color "#fabd2f" }

style.syntax["normal"]   = { common.color "#ebdbb2" }
style.syntax["symbol"]   = { common.color "#ebdbb2" }
style.syntax["comment"]  = { common.color "#928374" }
style.syntax["keyword"]  = { common.color "#fb4934" }
style.syntax["keyword2"] = { common.color "#fe8019" }
style.syntax["number"]   = { common.color "#d3869b" }
style.syntax["literal"]  = { common.color "#d3869b" }
style.syntax["string"]   = { common.color "#b8bb26" }
style.syntax["operator"] = { common.color "#8ec07c" }
style.syntax["function"] = { common.color "#fabd2f" }
