local style = require "core.style"
local common = require "core.common"

style.background        = { common.color "#192330" }
style.background2       = { common.color "#131a24" }
style.background3       = { common.color "#212e3f" }
style.text              = { common.color "#cdcecf" }
style.caret             = { common.color "#cdcecf" }
style.accent            = { common.color "#719cd6" }
style.dim               = { common.color "#738091" }
style.divider           = { common.color "#131a24" }
style.selection         = { common.color "#2b3b51" }
style.line_number       = { common.color "#39506d" }
style.line_number2      = { common.color "#71839b" }
style.line_highlight    = { common.color "#212e3f" }
style.scrollbar         = { common.color "#2b3b51" }
style.scrollbar2        = { common.color "#39506d" }
style.scrollbar_track   = { common.color "#192330" }
style.nagbar            = { common.color "#c94f6d" }
style.nagbar_text       = { common.color "#cdcecf" }
style.nagbar_dim        = { common.color "#a6364b" }
style.drag_overlay      = { common.color "#19233080" }
style.drag_overlay_tab  = { common.color "#719cd640" }
style.good              = { common.color "#81b29a" }
style.warn              = { common.color "#dbc074" }
style.error             = { common.color "#c94f6d" }
style.modified          = { common.color "#dbc074" }

style.syntax["normal"]   = { common.color "#cdcecf" }
style.syntax["symbol"]   = { common.color "#cdcecf" }
style.syntax["comment"]  = { common.color "#738091" }
style.syntax["keyword"]  = { common.color "#9d79d6" }
style.syntax["keyword2"] = { common.color "#c94f6d" }
style.syntax["number"]   = { common.color "#f4a261" }
style.syntax["literal"]  = { common.color "#f4a261" }
style.syntax["string"]   = { common.color "#81b29a" }
style.syntax["operator"] = { common.color "#63cdcf" }
style.syntax["function"] = { common.color "#719cd6" }
