local style = require "core.style"
local common = require "core.common"

style.background        = { common.color "#1a1b26" }
style.background2       = { common.color "#16161e" }
style.background3       = { common.color "#1e2030" }
style.text              = { common.color "#c0caf5" }
style.caret             = { common.color "#c0caf5" }
style.accent            = { common.color "#7aa2f7" }
style.dim               = { common.color "#565f89" }
style.divider           = { common.color "#101014" }
style.selection         = { common.color "#283457" }
style.line_number       = { common.color "#3b4261" }
style.line_number2      = { common.color "#737aa2" }
style.line_highlight    = { common.color "#1e2030" }
style.scrollbar         = { common.color "#292e42" }
style.scrollbar2        = { common.color "#3b4261" }
style.scrollbar_track   = { common.color "#1a1b26" }
style.nagbar            = { common.color "#f7768e" }
style.nagbar_text       = { common.color "#1a1b26" }
style.nagbar_dim        = { common.color "#c53b53" }
style.drag_overlay      = { common.color "#1a1b2680" }
style.drag_overlay_tab  = { common.color "#7aa2f740" }
style.good              = { common.color "#9ece6a" }
style.warn              = { common.color "#e0af68" }
style.error             = { common.color "#f7768e" }
style.modified          = { common.color "#e0af68" }

style.syntax["normal"]   = { common.color "#c0caf5" }
style.syntax["symbol"]   = { common.color "#c0caf5" }
style.syntax["comment"]  = { common.color "#565f89" }
style.syntax["keyword"]  = { common.color "#bb9af7" }
style.syntax["keyword2"] = { common.color "#f7768e" }
style.syntax["number"]   = { common.color "#ff9e64" }
style.syntax["literal"]  = { common.color "#ff9e64" }
style.syntax["string"]   = { common.color "#9ece6a" }
style.syntax["operator"] = { common.color "#89ddff" }
style.syntax["function"] = { common.color "#7aa2f7" }
